"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Code2, Copy, Check, Terminal, Database, Eye, Sparkles } from "lucide-react";

const TABS = [
  { key: "python_preprocessing", label: "Data Preprocessing", icon: <Code2 className="w-3.5 h-3.5" />, lang: "python" },
  { key: "python_model_fix", label: "Model Fix", icon: <Terminal className="w-3.5 h-3.5" />, lang: "python" },
  { key: "sql_query_fix", label: "SQL Query Fix", icon: <Database className="w-3.5 h-3.5" />, lang: "sql" },
  { key: "monitoring_script", label: "Monitoring", icon: <Eye className="w-3.5 h-3.5" />, lang: "python" },
];

function CopyButton({ text }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback
      const ta = document.createElement("textarea");
      ta.value = text;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <button
      onClick={handleCopy}
      className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md text-xs font-medium transition-all duration-150 cursor-pointer bg-white/10 hover:bg-white/20 text-white/70 hover:text-white"
    >
      {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
      {copied ? "Copied" : "Copy"}
    </button>
  );
}

export default function RemediationCode({ code, loading }) {
  const [activeTab, setActiveTab] = useState("python_preprocessing");

  if (loading) {
    return (
      <div className="rounded-xl border border-border bg-card overflow-hidden">
        <div className="flex items-center gap-3 px-6 py-4 border-b border-border">
          <div className="w-7 h-7 rounded-lg bg-muted flex items-center justify-center">
            <Sparkles className="w-4 h-4 text-foreground animate-pulse" />
          </div>
          <div>
            <p className="text-sm font-semibold text-foreground">Generating Remediation Code</p>
            <p className="text-xs text-muted-foreground">Gemini is writing Python & SQL fixes…</p>
          </div>
        </div>
        <div className="p-6 flex items-center justify-center">
          <div className="flex items-center gap-3 text-muted-foreground">
            <div className="w-5 h-5 border-2 border-muted-foreground/30 border-t-foreground rounded-full animate-spin" />
            <span className="text-sm">Analyzing bias patterns and generating fix code…</span>
          </div>
        </div>
      </div>
    );
  }

  if (!code) return null;

  const currentCode = code[activeTab] || "# No code generated for this section";

  return (
    <div className="rounded-xl border border-border bg-card overflow-hidden">
      {/* Header */}
      <div className="flex items-center gap-3 px-6 py-4 border-b border-border">
        <div className="w-7 h-7 rounded-lg bg-muted flex items-center justify-center">
          <Code2 className="w-4 h-4 text-foreground" />
        </div>
        <div className="flex-1 min-w-0">
          <p className="text-sm font-semibold text-foreground">Remediation Code</p>
          <p className="text-xs text-muted-foreground">Auto-generated by Gemini — Python & SQL fixes for detected bias</p>
        </div>
        <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full bg-[#caff3d]/15 text-[#a3cc2e]">
          AI Generated
        </span>
      </div>

      {/* Summary */}
      {code.summary && (
        <div className="px-6 py-3 border-b border-border bg-muted/30">
          <p className="text-xs text-muted-foreground leading-relaxed">{code.summary}</p>
        </div>
      )}

      {/* Tabs */}
      <div className="flex border-b border-border overflow-x-auto">
        {TABS.map((tab) => (
          <button
            key={tab.key}
            onClick={() => setActiveTab(tab.key)}
            className={[
              "flex items-center gap-1.5 px-4 py-2.5 text-xs font-medium whitespace-nowrap transition-all cursor-pointer border-b-2",
              activeTab === tab.key
                ? "border-foreground text-foreground bg-muted/40"
                : "border-transparent text-muted-foreground hover:text-foreground hover:bg-muted/20",
            ].join(" ")}
          >
            {tab.icon}
            {tab.label}
          </button>
        ))}
      </div>

      {/* Code Block */}
      <AnimatePresence mode="wait">
        <motion.div
          key={activeTab}
          initial={{ opacity: 0, y: 4 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -4 }}
          transition={{ duration: 0.15 }}
          className="relative"
        >
          <div className="absolute top-3 right-3 z-10">
            <CopyButton text={currentCode} />
          </div>
          <pre className="p-4 overflow-x-auto bg-[#0a0a0a] text-[#e4e4e7] text-xs leading-relaxed font-mono max-h-[400px] overflow-y-auto">
            <code>{currentCode}</code>
          </pre>
        </motion.div>
      </AnimatePresence>
    </div>
  );
}
